### ISSUE TITLE
BLT creates a new instance of Carabiner

### ISSUE THREAD

**Issue by VNRARA** [Deep-Symmetry/beat-link-trigger#139]
**Describe the bug**
BLT creates a new instance of carabiner everytime causing a firewall trigger notifcation every time it's connecting:

**To Reproduce**
Open BLT, connect with gear, connect with carabiner, get Firewall notification on Windows. 

**Expected behavior**
FIrewall notification just once for BLT or for carabiner.

**Screenshots**

![image](https://user-images.githubusercontent.com/3942672/183503073-436d9286-0d48-40de-ade4-e1b233c28f8c.png)

![image](https://user-images.githubusercontent.com/3942672/183503460-705f97d4-9c2d-4620-a12a-1d0811447e47.png)

**Exceptions and Stack Traces**

[blt.log](https://github.com/Deep-Symmetry/beat-link-trigger/files/9284697/blt.log)

**Desktop (please complete the following information):**
 - Beat Link Triger Version: Version: 7.0.1
 - Java Version:  11.0.15, OpenJDK 64-Bit Server VM, Amazon.com
 - OS: Windows 10 Home 21H2 5-‎8-‎2022 19044.1826

**Comment by brunchboy** [comment]
Yes, in order to do its magic of making Carabiner appear for you, BLT creates a new instance in a temporary location and runs it. If you do not want this to happen, then install Carabiner yourself wherever you would like it to exist, and configure it to start when you boot, or manually start it before running BLT, then BLT will use that one and not extract and run its own. Or, configure your firewall to automatically accept any instance of Carabiner wherever it is installed, and continue to use the auto-installed version.

**Comment by VNRARA** [comment]
Isn't carabiner depricated as a stand-alone?

**Comment by brunchboy** [comment]
Open Beat Control is a subset of Beat Link Trigger for use with programs like Max/MSP via Open Sound Control. It embeds Carabiner in the same way that BLT does. beat-carabiner is the library that both Beat Link Trigger and Open Beat Control use to embed Carabiner inside themselves and make it available when users request it. beat-carabiner will not do that if it finds you have already got Carabiner installed and running.

**Comment by VNRARA** [comment]
I believe I can use OSC as well (for use with touchdesigner's OSC-in). Thanks for your help :)

**Comment by brunchboy** [comment]
You could build an EXE if you like. There’s not enough of a real use case for Open Beat Control for me to build platform-native installers for it; it is for people who want to run on machines that don’t have screens or enough resources to run GUIs, and those machines are not going to be running macOS or Windows. And these days, a better answer for that is to use a Raspberry Pi 4, and run Beat Link Trigger using a headless VNC server, because that way you get all the features of BLT.
