### ISSUE TITLE
Rekordbox waveform dotted line in phrase data

### ISSUE THREAD

**Issue by oligriffiths** [Deep-Symmetry/beat-link-trigger#141]
**Problem**
The Rekordbox waveform shows a dotted line at the end of a phrase, usually at the end of a build up before the chorus drops:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/1246671/189992805-1bdf21bd-db71-4444-9c5c-01e6e47c76fe.png">
I can't find any info out about what this is, but it seems to almost always be the 4 beats preceding a drop/chorus coming back in, it would be super useful to be able to trigger on this info. It shows up in BLT in the player visualiser so the info must be exported over the network. This would be really useful to initiate a strobe or something similar right before the drop of a song.
Note that it is not always there:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/1246671/189993314-03d8b17c-2b8a-40e6-968a-908cba28e5a8.png">

**Describe the solution or new capability you’d like**
Having a specific trigger for this event would be awesome as it would allow for additional effects to be triggered when it's detected.

**Describe alternatives you've considered**
I don't even know what this is to find an alternative...

**Current Beat Link Trigger Version**
7.0.1

**Additional context**
None

**Comment by brunchboy** [comment]
The song structure tag is described here: https://djl-analysis.deepsymmetry.org/rekordbox-export-analysis/anlz.html#song-structure-tag

What you are describing is the fill section. This is described in the BLT user guide here: https://blt-guide.deepsymmetry.org/beat-link-trigger/7.0.1/shows_phrasetriggers#structure

If you paint a cue at the start of this section of your phrase trigger, it will run when that section begins. 

For this kind of exploratory discussion, please start Zulip topics rather than opening issues; if we decide a change to the software is warranted during that discussion then we'll decide to open an issue. You will reach far more of the user community there, very few people watch the repository.

**Comment by oligriffiths** [comment]
Noted, thanks for the response, much appreciated.
