### ISSUE TITLE
Player Status Window 

### ISSUE THREAD

**Issue by MAXQON** [Deep-Symmetry/beat-link-trigger#184]
Hey guys great job with that tool. I have a feature request for the Player Status Window. It would be great if it have a full screen mode for a second screen . It's not really a problem more like a nice to have feature

**Comment by brunchboy** [comment]
Thanks! Please discuss ideas like this in the [Zulip community](https://deep-symmetry.zulipchat.com) and only open issues if asked to there. Also, feel free to experiment with this, and let us know on Zulip if you find a good approach to implement it. I’m unlikely to pursue it because layout of that window is finicky, but the great thing about open source is you don’t have to wait for anyone to build something you want, you can build it yourself!
