### ISSUE TITLE
Play button on XDJ stopped working since using beat link

### ISSUE THREAD

**Issue by alexhorton** [Deep-Symmetry/beat-link-trigger#69]
### Version of Beat Link Trigger

0.5.2

### Version of Java

version that came with the dmg installer

### Version of OS

OS 10.14.3

### The issue you're experiencing

i cant see how this could be connected in anyway and maybe its coincidence, except i replaced the board on the device and it didnt fix it. since using XDJ1000mk2 with beat link trigger the play button on one of the devices no longer works, its like that part of the transport has been swoitched off in software.  ANY possibility this could have happened due to the (awesome) trigger software? not looking for blame but am looking to fix issue and continue using beatlink with confidence

**Comment by brunchboy** [comment]
I can’t imagine any possible way that could happen.

**Comment by brunchboy** [comment]
But unfortunately, asking here is the wrong place; I don’t have (and never have had) any access to internal Pioneer documentation or schematics, so I can’t speculate about how something like that might occur.

Beat Link doesn’t make any changes to the players’ configuration or hardware, though, so if interacting with it over the network can break the hardware, that is an issue that needs to be fixed by Pioneer.

The only plausible explanation, however, is coincidental hardware failure.

**Comment by alexhorton** [comment]
this is great to know, thanks!

**Comment by brunchboy** [comment]
You’re welcome! I’m sorry you have to deal with a busted Play button though. 😞 

If you are curious about the full details of how Beat Link Trigger communicates with the players, it is explained in detail in the analysis papers of the [dysentery](https://github.com/Deep-Symmetry/dysentery#dysentery) and [crate-digger](https://github.com/Deep-Symmetry/crate-digger#crate-digger) projects.
