### ISSUE TITLE
Send SMPTE position data to @vanvught's LTC Generator via osc

### ISSUE THREAD

**Issue by drummerclint** [Deep-Symmetry/beat-link-trigger#87]
http://www.orangepi-dmx.org/orange-pi-smpte-timecode-ltc-reader-converter
https://github.com/vanvught/rpidmx512
reference to http://www.orangepi-dmx.org/orange-pi-smpte-timecode-ltc-reader-converter/internal-generator/run-time-osc-messages for osc commands

cc @vanvught

**Comment by brunchboy** [comment]
This won’t require any changes to BLT itself, but once we have a collection of expressions that work well for @drummerclint I will want to add them to the User Guide as another integration example, along with links explaining how to create one of these devices.

**Comment by brunchboy** [comment]
All right, here is a draft integration attempt. @drummerclint I changed the port number from the 8001 that you mentioned to 8000 because that is what @vanvught says the OSC server listens on in the documentation you linked above. If for some reason that is not true on your specific build, then you will want to change it back. This is in the show’s `Came Online` expression, and hopefully it will be clear how to edit it.

The show file is attached to this comment, you will want to unzip it and open it in BLT. Then you will want to load the tracks you want to test with onto your player, then import them into the show from the player, and copy the `Loaded` and `Unloaded` expressions from my sample track to each track you want to test with. When you are pasting the `Loaded` expression into your new track’s expression editor, it should be clear where you can edit the `frame-rate` and `offset` values to the ones you want to use for that track. If for some reason you need to change the hostname used as a prefix in the OSC commands (I can’t understand why that is there at all), that is at the top of the show’s `Shared Functions`.

Once you have your own tracks set up and working properly, you can delete my sample track from the show, its only purpose was to let you copy its `Loaded` and `Unloaded` expressions.

I am sure questions will come up, but hopefully this is a start!

[OrangeSMPTE.bls.zip](https://github.com/Deep-Symmetry/beat-link-trigger/files/4007578/OrangeSMPTE.bls.zip)

**Comment by brunchboy** [comment]
@drummerclint here is the latest version of the `build-orangepi-position-listener` function, the last function in the show’s Shared Functions, which should work properly with reverse play as well.

```clojure
(defn build-orangepi-position-listener
  "Creates a `TrackPositionListener` that will cause the SMPTE linear
  timecode output by the OrangePi-DMX listening on the specified
  `osc-client` connection to follow the position and speed of the
  track loaded in the specified `player`, with the specified
  `frame-rate` in frames per second and `offset` in hours."
  [osc-client player frame-rate offset]
  (let [prefix   (str "/" orangepi-dmx-hostname "/tc/") ; All OSC commands start with this string.
        reversed (atom false) ; Tracks whether the timecode is running backwards.
        listener (reify org.deepsymmetry.beatlink.data.TrackPositionListener
                   (movementChanged [this position-update]
                     (when position-update  ; Make sure we have some information
                       ;; Update the current playback pitch. The OrangePi-DMX uses values
                       ;; that are 1.0 less than those used by Beat Link.
                       (osc/osc-send osc-client (str prefix "pitch") (float (- (.pitch position-update) 1.0)))
                       (when (not= @reversed (.reverse position-update))
                         ;; Send a direction command if the player direction differs from how the timecode is running.
                         (reset! reversed (.reverse position-update))
                         (osc/osc-send osc-client (str prefix "direction/" (if @reversed "backward" "forward"))))
                       ;; Jump timecode to the new position, and reflect whether we are playing or stopped.
                       (let [command  (if (and (.playing position-update)
                                               (pos? (.pitch position-update)))
                                        "start/"  ; We are playing at a non-zero pitch.
                                        "goto/") ; We are stopped, or pitch is zero, effectively the same.
                             timecode (ms-to-timecode-segments (.milliseconds position-update) frame-rate offset)]
                         (osc/osc-send osc-client (str prefix command timecode))))))]
    (osc/osc-send osc-client (str prefix "rate/set/" frame-rate)) ; Tell the SMPTE generator the frame rate.
    (osc/osc-send osc-client (str prefix "direction/forward")) ; And start out assuming we will be playing forward.
    listener))  ; Return the `TrackPositionListener` we built.
```

**Comment by brunchboy** [comment]
Please let me know if that seems to work, and I will write this up in the user guide! 😄 Here is an updated copy of the full show, for my own reference (and for anyone following this issue who did not get all the private communication between us this past few days).
[OrangeSMPTE.bls.zip](https://github.com/Deep-Symmetry/beat-link-trigger/files/4014924/OrangeSMPTE.bls.zip)

**Comment by drummerclint** [comment]
Hey James, the beat link show works well!  
Can you make a trigger version as well, where I don't need to map it to a specific track, just to what ever deck either I force it to watch or first on air player.  For songs where I have actual tracks for, I'll do those in a show setting, but for on the fly moments, I'd need to use a trigger.

**Comment by brunchboy** [comment]
All right, @drummerclint here is a crack at a BLT configuration that includes a trigger-based integration with the OrangePi SMPTE generator. I can’t be positive it is working, because I don’t have one of those to test with, but it is not crashing, and the few things I can see in the expression locals look promising to me.

I know you had started working on this yourself, but the approach required for working in the Triggers world is so fundamentally different from the Show world that I had to rewrite significant parts of the code, and you are probably better off starting from this file than what you have been experimenting with.

> ⚠️ Be sure to save your existing Beat Link Trigger configuration to a file if you have anything in there you want to be able to get back to, because this is a complete configuration file that will replace all your triggers and expressions. [OrangePiSMPTE.blt.zip](https://github.com/Deep-Symmetry/beat-link-trigger/files/4052300/OrangePiSMPTE.blt.zip)

You will also want to install the latest preview build of BLT before trying this because I made a small improvement to the underlying Beat Link `TimeFinder` API to make this code easier to write. There is nothing like an actual use case to help fleshing out an API.

As configured, the trigger will track the master player, and send time code to match it as long as it is On-Air. If you don’t want to trust the on-air setting, change the trigger’s Enabled filter to Always. You can also change which player it follows to a specific player if you would prefer, but the trigger is capable of tracking changes between players and re-registering the track position listener to the appropriate player as needed. That is what makes it so different from the Show situation.

Please let me know if this works! If it does, it’s time to write these up and start putting a bow around another release of BLT.

**Comment by brunchboy** [comment]
This is released, but I will leave the issue open until @drummerclint tells me he has no more tweaks to make to the user guide section for a future release.

**Comment by brunchboy** [comment]
@drummerclint is there anything left to do fort this?

**Comment by drummerclint** [comment]
@brunchboy I think we're good!  Great job to you and @vanvught!  I'd go primarily with a song based trigger and keep the traditional style trigger as a secondary.

**Comment by brunchboy** [comment]
OK, sounds good, I will re-order them since the show based approach is easier to manage. And it seems people are using it, I got a request to be able to organize cues hierarchically on the Gitter chat, which tells me that someone is actually using cues! 😄

**Comment by drummerclint** [comment]
Ahaha it's just because of the nature of timecode.  It's going to be very song specific so it would make sense to go with that method.  I saw that request, good to hear people are putting all that hard work you've invested in to good use!
